package com.demo.reservation.dto;

public enum ReservationTerrainState {

	DISPONIBLE, 
	NON_DISPONIBLE_RESERVE,
	NON_DISPONIBLE_PREVISION_PLUIE,
	NON_DISPONIBLE_JOUEURS_OBLIGAOIRE,
	NON_DISPONIBLE_NBR_JOUEURS_INF_2,
	NON_DISPONIBLE_NBR_JOUEURS_SUP_8,
	NON_DISPONIBLE_DATE_RESERVATION_ERRONEES

}
